spring:
  application:
    name: sigtran-server

server:
  port: 8082

response:
  imsi:
    delays: 0, 1000, 2000, 0, 4000, 5000
    file: /home/iftekhar/projects-my/location-finder/sigtran-server/src/main/resources/imsi-response.json
